# Generated by Django 5.2.17 on 2026-08-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True)),
                ('nama_normalized', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'commodity',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255)),
                ('tanggal_import', models.DateTimeField(auto_now_add=True)),
                ('sheet_name', models.CharField(blank=True, max_length=100)),
                ('jumlah_baris', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('proses', 'Proses'), ('berhasil', 'Berhasil'), ('gagal', 'Gagal')], default='proses', max_length=20)),
                ('pesan_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'import_batch',
                'ordering': ['-tanggal_import'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kabkota', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('provinsi', models.CharField(blank=True, max_length=100)),
                ('pulau', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'region',
                'ordering': ['kode_kabkota'],
            },
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('minggu', models.PositiveIntegerField()),
                ('bulan', models.PositiveIntegerField(blank=True, null=True)),
                ('tanggal_awal', models.DateField(blank=True, null=True)),
                ('tanggal_akhir', models.DateField(blank=True, null=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'report_period',
                'ordering': ['-tahun', '-minggu'],
                'constraints': [models.UniqueConstraint(fields=('tahun', 'minggu'), name='unique_report_period')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyIPH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perubahan_iph', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fluktuasi_tertinggi', models.CharField(blank=True, max_length=150)),
                ('nilai_cv', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
                ('disparitas_harga', models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('naik', 'Naik'), ('turun', 'Turun'), ('stabil', 'Stabil')], max_length=20)),
                ('upaya_pemda', models.TextField(blank=True)),
                ('saran_pemda', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_iph', to='iph.importbatch')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_iph', to='iph.reportperiod')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_iph', to='iph.region')),
            ],
            options={
                'db_table': 'weekly_iph',
                'ordering': ['-period', 'region'],
            },
        ),
        migrations.CreateModel(
            name='CommodityContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_andil', models.DecimalField(decimal_places=9, max_digits=15)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='iph.commodity')),
                ('weekly_iph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_contributions', to='iph.weeklyiph')),
            ],
            options={
                'db_table': 'commodity_contribution',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyiph',
            constraint=models.UniqueConstraint(fields=('region', 'period'), name='unique_region_period'),
        ),
        migrations.AddConstraint(
            model_name='commoditycontribution',
            constraint=models.UniqueConstraint(fields=('weekly_iph', 'commodity'), name='unique_weekly_commodity'),
        ),
    ]
