# Generated by Django 5.2.17 on 2026-08-28 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPHSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField()),
                ('bulan', models.PositiveIntegerField()),
                ('minggu', models.PositiveIntegerField()),
                ('nilai_iph', models.DecimalField(decimal_places=4, max_digits=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_iph', to='iph.region')),
            ],
            options={
                'db_table': 'iph_series',
                'ordering': ['tahun', 'bulan', 'minggu'],
                'constraints': [models.UniqueConstraint(fields=('region', 'tahun', 'bulan', 'minggu'), name='unique_series_region_period')],
            },
        ),
    ]
