# Generated by Django 5.2.17 on 2026-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iph', '0002_iphseries'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportperiod',
            name='unique_report_period',
        ),
        migrations.AddConstraint(
            model_name='reportperiod',
            constraint=models.UniqueConstraint(fields=('tahun', 'bulan', 'minggu'), name='unique_report_period'),
        ),
    ]
